name: Automerge

on:
  workflow_dispatch:
  schedule:
    # You can setup schedule here
    - cron: '0 0 * * *'

env:
  # replace "spandey1296" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://coder2hacker:${{secrets.GITHUB_TOKEN}}@github.com/coder2hacker/Explore-open-source

  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: main

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/coder2hacker/master_repo.git

  # replace "master" with your master branch name
  MASTER_BRANCH: master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with master
      run: |
        git clone ${{env.MY_REPO}} -b ${{main}} tmp
        cd tmp
        git config user.name "spandey1296"
        git config user.email "shivant47@gmail.com"
        git config pull.rebase false
        git pull ${{main}} ${{main}}
        git push
